name: Automatic Deployment Pipeline

on:
  push:
    branches:
      - master  

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    # Check out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Set up ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Check up AWS credentials
        run: aws sts get-caller-identity

      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPOSITORY }}

    # Build the Image
      - name: Build Docker image
        run: |
          docker build -t analytics:latest .
        working-directory: analytics/

      - name: Tag Docker image
        run: |
          docker tag analytics:latest ${{ secrets.AWS_ECR_REPOSITORY }}:latest
        working-directory: analytics/

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ECR_REPOSITORY }}:latest
        working-directory: analytics/